encoding: utf-8

# seo
title: Tsingxu Blog
description: Tsingxu Blog
keywords: Tsingxu,Blog,PHP,,Html,Css,Js
author: Tsingxu

# "","/blog"
context: ""
"siteMapPrefix": "http://blog.tsingxu.net"

## 文章url前缀 context/自定义，下面的context为''
permalink: /posts/:year/:month/:day/:title.html

copyright: 2016
record: "皖ICP备16016174号"

coderay:
  coderay_tab_width: 4