encoding: utf-8

# seo
title: Tsingxu Blog
description: Tsingxu Blog
keywords: Tsingxu,Blog,PHP,Html,Css,Js,Nginx
author: Tsingxu

context: ""
baseurl: /blog
categoriesurl: /blog/pages/categories
searchurl: /blog/pages/search
linksurl: /blog/pages/links
chaturl: /blog/pages/chat
abouturl: /blog/pages/about


cssurl: /blog/static/css
jsurl: /blog/static/js

permalink: /posts/:year/:month/:day/:title.html