encoding: utf-8
title: 标题

baseurl: /blog
categoriesurl: /blog/pages/categories
searchurl: /blog/pages/search
linksurl: /blog/pages/links
chaturl: /blog/pages/chat
abouturl: /blog/pages/about

# 用于多说评论 填入留言板地址
# realchaturl: http://xxx.xxx/simple-jekyll-theme/pages/chat

cssurl: /blog/static/css
jsurl: /blog/static/js

permalink: /posts/:title.html